### ISSUE TITLE
Error in event handler for runtime.onMessage: TypeError: Cannot read property 'orgId' of null

### ISSUE THREAD

**Issue by ajaylankipalle** [xgeek-net/salesforce-mass-editor#12]
Issue in lightning: For fist time it worked after that it is not working:

Error in event handler for runtime.onMessage: TypeError: Cannot read property 'orgId' of null
    at chrome-extension://mnmlmkmjjhpbfemhmhpcpfkdlgadbigf/dist/js/main.min.js:20:1873
    at MassMetaRequest.requestMetaData (chrome-extension://mnmlmkmjjhpbfemhmhpcpfkdlgadbigf/dist/js/main.min.js:20:2515)
    at MassMetaRequest.restoreMetaData (chrome-extension://mnmlmkmjjhpbfemhmhpcpfkdlgadbigf/dist/js/main.min.js:20:1810)
    at chrome-extension://mnmlmkmjjhpbfemhmhpcpfkdlgadbigf/dist/js/main.min.js:23:9524

**Comment by xgeek-net** [comment]
Hi, @ajaylankipalle 

Make sure **“Require HttpOnly attribute”** option in **"Session Settings"** is not checked.

Reference : 
https://www.xgeek.net/salesforce/salesforce-mass-editor-chrome-extension/#notice

**Comment by xgeek-net** [comment]
Hi, @ajaylankipalle 
This issue is fixed in latest version(v3.1.0), please update it and try again.
