### ISSUE TITLE
metadata index error

### ISSUE THREAD

**Issue by pillsnberries** [xgeek-net/salesforce-mass-editor#16]
started receiving this error when attempting to use Mass Editor on list view. not sure how to resolve.

_Metadata error occurred, please reload metadata index and try again._

**Comment by xgeek-net** [comment]
Hi, @pillsnberries 

Refresh metadata index and try again as below.

https://www.xgeek.net/ja/salesforce/salesforce-mass-editor-chrome-extension/#reload-metadata-index

If it still doesn't work, please "Report issue on Github" from extension menu with process log, that will be very helpful.
