### ISSUE TITLE
Button does not appear in Lightning

### ISSUE THREAD

**Issue by tcalero1** [xgeek-net/salesforce-mass-editor#17]
The Mass Edit button does not appear in Lightning for custom objects. Steps taken:

- Instructed the user to refresh the metadata index (https://www.xgeek.net/ja/salesforce/salesforce-mass-editor-chrome-extension/#reload-metadata-index), but the link is not responsive to any clicks 

- I ensured that the user's profile includes API Enabled permission

**Comment by xgeek-net** [comment]
Hi, @tcalero1 

Did you get any process log on click "Report Issue on Github" button as below? 
https://github.com/xgeek-net/salesforce-mass-editor/issues/15

**Comment by xgeek-net** [comment]
@tcalero1 
Hi, This issue is fixed in latest version(v3.1.0).
