### ISSUE TITLE
Mass Editor Not Working

### ISSUE THREAD

**Issue by GreatPlains** [xgeek-net/salesforce-mass-editor#18]
I use Google Extension for Salesforce Mass Editing. Since last week, it will no longer sync. I keep hitting reload metadata but it just keep saying reload failed. And when I click report issue, it just spins and doesnt do anything. Is there something going on?

**Comment by xgeek-net** [comment]
Hi, @GreatPlains 

Does any javascript error occurred when you click report issue button? And which edition are you using? Classic, or Lightning?

**Comment by GreatPlains** [comment]
No java error when I do it.  We are using Classic.

Jacque Ell
Project Management Specialist
402.456.6554
[cid:image001.jpg@01D2D087.35099AF0]
www.gpcom.com<http://www.gpcom.com/>
Accountability • Community • Integrity • Quality • Service • Teamwork

**Comment by xgeek-net** [comment]
Hi, @GreatPlains 

Can you click "Report Issue on Github" menu as below after reproduced error? Then you'll get some  app log and if you can send it to me, that will be helpful to look out what is happening

![report-issue-on-github](https://user-images.githubusercontent.com/5466487/42820506-509d579e-8a11-11e8-9739-5207010bde0c.png)

**Comment by GreatPlains** [comment]
When I click Report issue on GitHub, it just spins, nothings happens.  It can sit for minutes and nothing. Is that supposed to happen?

Jacque Ell

**Comment by xgeek-net** [comment]
Did you click Mass Editor icon on Salesforce List view page? It will open a Github new issue page with app log.

**Comment by xgeek-net** [comment]
@GreatPlains Click it as below: 

![report issue](https://user-images.githubusercontent.com/5466487/42821273-21ff5642-8a13-11e8-929c-19de8cf7fdd3.gif)

**Comment by GreatPlains** [comment]
That Mass Editor link isn’t even showing up any more in Salesforce.  I noticed it was gone last week.
 I have uninstalled this extension and reinstalled it but still get the same results.

When I click the icon in Chrome, it brings this up. When I click report issue, it spins and does nothing.

[cid:image006.jpg@01D41DAA.6F4A1980]

When I click Reload metadata index it gives me reload failed.

[cid:image007.jpg@01D41DAA.6F4A1980]

Jacque Ell
Project Management Specialist
402.456.6554
[cid:image001.jpg@01D2D087.35099AF0]
www.gpcom.com<http://www.gpcom.com/>
Accountability • Community • Integrity • Quality • Service • Teamwork

**Comment by xgeek-net** [comment]
Did someone change your user's permission? 
If it works for org system admin, that means your user has not enough permission for those objects.
And if it doesn't work even for org system admin, that (maybe) means someone disabled org session settings.
@GreatPlains

**Comment by GreatPlains** [comment]
I am our Salesforce Admin and we have not changed any permissions or settings recently. Any idea what setting would control this so I can go look?  I am the main admin, but we do have another admin for development, but I do not think they changed anything either.

Jacque Ell
Project Management Specialist
402.456.6554
[cid:image001.jpg@01D2D087.35099AF0]
www.gpcom.com<http://www.gpcom.com/>
Accountability • Community • Integrity • Quality • Service • Teamwork

**Comment by xgeek-net** [comment]
Can you check “Require HttpOnly attribute” option in “Session Settings”? Make sure it is not checked.
And does it work on Account or Contact list view page?

@GreatPlains

**Comment by GreatPlains** [comment]
It was unchecked and the Mass Editor doesn’t show on any object list view in SF.

Jacque Ell
Project Management Specialist
402.456.6554
[cid:image001.jpg@01D2D087.35099AF0]
www.gpcom.com<http://www.gpcom.com/>
Accountability • Community • Integrity • Quality • Service • Teamwork

**Comment by xgeek-net** [comment]
Hmmm...Which url shows for you when you open Account list view?
And no any page is opened when you click as blow? That's really odd.
https://github.com/xgeek-net/salesforce-mass-editor/issues/18#issuecomment-405587422

@GreatPlains

**Comment by GreatPlains** [comment]
Attached is a video.
My custom SF domain is what is being used.  And it just sits and spins when clicking the Github link.  Yesterday I let it spin for 5 minutes before closing it.

Jacque Ell
Project Management Specialist
402.456.6554
[cid:image001.jpg@01D2D087.35099AF0]
www.gpcom.com<http://www.gpcom.com/>
Accountability • Community • Integrity • Quality • Service • Teamwork

**Comment by xgeek-net** [comment]
>My custom SF domain is what is being used

Which kind of SF domain are you using? @GreatPlains

**Comment by GreatPlains** [comment]
gpcom.my.salesforce.com

Jacque Ell
Project Management Specialist
402.456.6554
[cid:image001.jpg@01D2D087.35099AF0]
www.gpcom.com<http://www.gpcom.com/>
Accountability • Community • Integrity • Quality • Service • Teamwork

**Comment by xgeek-net** [comment]
You domain seems ok, can you provide the below two screenshots without any security information : 
1. Any object list view page.
2. screenshot after you click "Report Issue on Github" menu.
@GreatPlains

**Comment by GreatPlains** [comment]
[cid:image001.png@01D41F31.C909D3B0]


After we click Report issue, it doesn’t do anything. It can sit and spin for 5+ minutes and never do anything.
[cid:image002.png@01D41F31.C909D3B0]

Jacque Ell
Project Management Specialist
402.456.6554
[cid:image001.jpg@01D2D087.35099AF0]
www.gpcom.com<http://www.gpcom.com/>
Accountability • Community • Integrity • Quality • Service • Teamwork

**Comment by xgeek-net** [comment]
@GreatPlains 
There is nothing attached in your comment, does your network block something?

**Comment by GreatPlains** [comment]
I had two images inside the email.

Jacque Ell
Project Management Specialist
402.456.6554
[cid:image001.jpg@01D2D087.35099AF0]
www.gpcom.com<http://www.gpcom.com/>
Accountability • Community • Integrity • Quality • Service • Teamwork

**Comment by xgeek-net** [comment]
Hi, @GreatPlains 
You need to inside images from below Github page but not email.
https://github.com/xgeek-net/salesforce-mass-editor/issues/18

**Comment by GreatPlains** [comment]
![1](https://user-images.githubusercontent.com/5099348/43087589-d42c8640-8e65-11e8-93ec-4f571cee9d27.png)
![2](https://user-images.githubusercontent.com/5099348/43087591-d43dafd8-8e65-11e8-9eb9-4ad40c56301f.png)

**Comment by xgeek-net** [comment]
@GreatPlains 

Seems you are opening Projects recent view page, but not Projects **list view** , you can click "go!" button to open list view and try again.

**Comment by GreatPlains** [comment]
My Java did an update last night and now I can see it. So it looks to be just a Java issue?

**Comment by xgeek-net** [comment]
@GreatPlains 
I don't think so but maybe it was a Chrome issue.
