### ISSUE TITLE
Remote Authorization stuck in processing

### ISSUE THREAD

**Issue by mehansen82** [xgeek-net/salesforce-mass-editor#29]
When I try to access Mass Editor it pops up a window for Remote Authorization that gets stuck in processing. I have enabled Custom Domain and reloaded the Metadata Index.  We recently moved to Single Sign on authentication through Okta. Would that prevent me from using this plugin?

**Comment by xgeek-net** [comment]
Hi, @mehansen82 
Thank you for your report, it's a bug caused by Chrome security policy updated recently, will fix it ASAP.
BTW, you can use it on Classic to avoid this bug until I fixed it.

**Comment by xgeek-net** [comment]
Hi, @mehansen82 , this issue is fixed at the latest version (v3.1.6), can you try it again?

**Comment by mehansen82** [comment]
I confirmed this is fixed and I’m able to use Mass Editor – thank you so much!
