### ISSUE TITLE
What is the PC keyboard shortcut for Paste All

### ISSUE THREAD

**Issue by guggesn** [xgeek-net/salesforce-mass-editor#3]
Hi, Lin,
What is the keyboard shortcut command to paste all in Windows? See my screenshot, attached.
![for lin shortcut command](https://user-images.githubusercontent.com/34512761/34415830-b875f3c2-ebbe-11e7-891d-54c27317e55f.png)

I think that is an Apple keyboard icon? I tried CRTL-WINDOWSLOGO-V but that's doesn't work.

Thanks, Susan

**Comment by xgeek-net** [comment]
Hi, Susan,
Do you have tried **CTRL + V** ? 
@guggesn

**Comment by guggesn** [comment]
I did try last week, no luck, but today, yes!

Thank you so much, this is a great app.

Regards,

~Susan


*Susan Guggenheim*
Manager - Client Relations
*Softer*Ware, Inc

Schedule a chat with me <https://sguggenheim.youcanbook.me>

Cell: 215-284-6038

Tollfree: 800-220-3537  ext. 360

email: sguggenheim@softerware.com
http://www.SofterWare.com <http://www.softerware.com/>


Why DonorPerfect rocks the NTEN chart!
<https://www.donorperfect.com/PDF/NTEN-Infographic.pdf>
