### ISSUE TITLE
MassEditor does not start.

### ISSUE THREAD

**Issue by maikomisawa0619** [xgeek-net/salesforce-mass-editor#30]
When you press the Mass Editor button, the pop-up displays "process ..." and MassEditor does not start.

![B793q5ca4b9f93863c68d2deb7a0b](https://user-images.githubusercontent.com/36220265/55484857-3bb5cf80-5664-11e9-99ec-d869d92eac2d.png)

**Comment by xgeek-net** [comment]
Hi, it is a bug and I'm fixing it, reference the below issue: 
https://github.com/xgeek-net/salesforce-mass-editor/issues/29

**Comment by xgeek-net** [comment]
Hi, @maikomisawa0619 , this issue is fixed at the latest version (v3.1.6), can you try it again?

**Comment by maikomisawa0619** [comment]
It was possible. Thank you very much.
