### ISSUE TITLE
Cannot see 'delete' button

### ISSUE THREAD

**Issue by ninojolly** [xgeek-net/salesforce-mass-editor#6]
Firstly, I love  this  tool! such as timesaver, I've told everyone i know about it and they all love it!

I notice sometimes I dont see the clone or delete buttons on pages. Is it due to particular data or access that prevents those buttons?

![image](https://user-images.githubusercontent.com/36003102/35629666-3594fff6-066d-11e8-8a5b-75a6d127bef8.png)

**Comment by xgeek-net** [comment]
Hi, @ninojolly 
Thanks for using my Mass Editor. 

You can try the below way to fix it:
1. Make sure the user you login has creatable and deletable permission on the Object.
2. Refresh Metadata index (as you uploaded), and refresh the list view page and try again.

BTW. Other guys fixed this kind of issue by the same way.
