### ISSUE TITLE
The record type of the opportunity

### ISSUE THREAD

**Issue by HiroMatsushima** [xgeek-net/salesforce-mass-editor#9]
The record type of the opportunity is not a user interface that can be changed all at once.
How do you make it changeable?

**Comment by xgeek-net** [comment]
Hi, @HiroMatsushima 

Thank you for using Mass Editor and you feedback.
Seems it is a bug and I'll fix it ASAP.

**Comment by xgeek-net** [comment]
Hi, @HiroMatsushima 

This issue has been fixed in v3.0.2, try it again.

Regards.
